version: "3.9"

services:
  qwen-image-series-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18808:8000"
    volumes:
      - /mnt/data/models/Qwen:/Qwen/models
    environment:
      - QWEN_IMAGE_EDIT_LOCATION=/Qwen/models/Qwen-Image-Edit-2509
      - QWEN_IMAGE_LOCATION=/Qwen/models/Qwen-Image
      - CUDA_VISIBLE_DEVICES=2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count:  1
              capabilities: ["gpu"]
